sudo: false

language: go
go:
  - 1.9.x
  - 1.x

git:
  depth: 1

install: true

notifications:
  email: false

install:
  - go get github.com/trasiercom/trasier-client-go
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go vet
  - $HOME/gopath/bin/goveralls -repotoken hS6BSwZpBQOn49C0WcLCf2OmQFY1it2bY