sudo: false

language: go
go:
  - 1.9.x
  - 1.x

git:
  depth: 1

install: true

notifications:
  email: false

install:
  - go get github.com/trasiercom/trasier-client-go

script:
  - go test -v ./...
